#!/bin/bash
STOCK_FILE="/home/$USER/OS-SE-p20240001/final-exam/partD_secure/stock.txt"
LOG_FILE="/home/$USER/OS-SE-p20240001/final-exam/partD_secure/sales.log"
LOCK_FILE="/home/$USER/OS-SE-p20240001/final-exam/partD_secure/stock.lock"
BUYER=$1
QTY=$2

if [[ ! "$QTY" =~ ^[0-9]+$ ]] || [ "$QTY" -le 0 ]; then
    echo "Invalid quantity."
    exit 1
fi

# LIVE CURVEBALL: Enforce the Cap
PURCHASE_CAP=8

if [ "$QTY" -gt "$PURCHASE_CAP" ]; then
    echo "Order rejected: Quantity $QTY exceeds per-buyer cap of $PURCHASE_CAP."
    exit 1
fi

(
    flock -x 200
    STOCK=$(cat "$STOCK_FILE")
    if [ "$STOCK" -ge "$QTY" ]; then
        sleep 0.1 
        NEW_STOCK=$((STOCK - QTY))
        echo "$NEW_STOCK" > "$STOCK_FILE"
        echo "p20240001 - $BUYER bought $QTY Widget(s)" >> "$LOG_FILE"
    fi
) 200>"$LOCK_FILE"
